CREATE TABLE Wargear (
    Wid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Type VARCHAR2(10) CHECK (Type IN ('Range', 'Melee', 'Text')),
    Slot1 number NOT NULL,
    Slot2 number NOT NULL,
    Slot3 number NOT NULL,
    Slot4 number NOT NULL,
    Slot5 number NOT NULL,
    TraitsCount NUMBER NOT NULL,
    SpecialRulesCount NUMBER NOT NULL
);